### ISSUE TITLE
Improve Natural Language Processing

### ISSUE THREAD

**Issue by caseyjohnsonwv** [caseyjohnsonwv/chaindog#11]
In #2, we left an item for later implementation. There are also things that could be improved otherwise.

- [ ] Extract a time keyword such as "hours," or "minutes." Convert to minutes on the backend.
- [x] #12
- [ ] Implement actual NLP rather than just fuzzy matching everything.
- [ ] #13
- [ ] Properly extract an action (create, update, delete) rather than using regular expressions.

EDIT: It may be worth exploring [AWS Comprehend](https://aws.amazon.com/comprehend) - this is cheaper than I thought.
