### ISSUE TITLE
Allow All SMS Interactions to Handle Ambiguity Gracefully

### ISSUE THREAD

**Issue by caseyjohnsonwv** [caseyjohnsonwv/chaindog#13]
Currently, the entire application is stateless: requests and responses have to be specified in their entirety. It would be nice if they didn't.

For example, the user requests a watch for "Batman at Six Flags."
1. Create a partial watch "transaction" with their phone number and commit it to the DB.
2. Pull every park they could have meant and ask them to specify. Repeat as needed until only one park.
3. Update the transaction in the DB.
4. Repeat step 2 for ride name if needed.
5. Finish creating the watch in the DB, setting its expiration based on the time it was finished.

---

## Architecture To Enable This Change

I think this will require a separate Dynamo table for "Transactions" - this can store metadata about the user's interactions with the bot as well as a partial watch that is being populated through the conversation:
```
{
  "phone_number" : "+11234567890",
  "user_message" : "Watch Batman at Six Flags.",
  "our_message" : "Which park are you referring to? Six Flags Great Adventure, Six Flags Great America, [etc.]",
  "timestamp_utc" : "2022-09-12T02:58:00.123456+00:00",
  "expecting_yn_response" : False,
  "expected_responses": ["Six Flags Great Adventure", "Six Flags Great America", ...],
  "watch" : {
    (all the fields of a normal watch object, but null if needed)
  }
}
```
With each successive message, we can populate the `watch` object, finally adding it to the "Watches" table in Dynamo when none of its fields are null. This way, we can always assume a watch in the "Watches" table is complete and valid.

---

## Implementation

- [ ] Add "Transactions" table (PK = phone_number) + IAM permissions to Terraform
- [ ] Modify fuzzy matching to return all options above the specified threshold, then make Watch Lambda create / update a transaction if there are multiple good options.
- [ ] Make Watch Lambda check for transactions in progress on each invocation. Use the `expected_responses` to determine if the user has answered the question. Determine what question to ask next based on the null fields remaining in the nested `watch` object. If no fields are null, write the watch to the "Watches" table.
- [ ] Prune incomplete transactions that are older than 5 minutes (?) with a new Lambda function. Text the user that we didn't create the watch. This can be invoked by the same SNS topic that triggers the Notification Lambda.
