### ISSUE TITLE
Refactor for Error Handling System-Wide

### ISSUE THREAD

**Issue by caseyjohnsonwv** [caseyjohnsonwv/chaindog#25]
Related to #7 - the current architecture limits all SMS interaction to one Lambda function, invoked by a synchronous API call. At scale, this will be more cost-effective as a container rather than a serverless function. It will also be easier to perform proper error handling in a long-running container.

1. Twilio invokes the API endpoint
2. API endpoint invokes a Lambda, which pushes the payload to a queue and returns an empty 200 OK to Twilio.
3. A long-running ECS container consumes the queue, performs NLP etc., then invokes the SMS Lambda.

This has a few advantages:
- No more worrying about Lambda package size OR memory / runtime for intensive NLP processes.
- SMS message response templates can be loaded into the NLP container from a CSV / XLSX file in S3.
- Cleaner architecture for successes AND failures with all outbound messages being sent via the SMS Lambda.

## Implementation
- [ ] Create long-running NLP loop that can poll SQS and publish to SNS.
- [ ] Containerize the NLP code and add ECS task / service to the IaC config.
- [ ] Add an SQS queue to the IaC config.
- [ ] Modify the Watch Lambda source to simply push messages to the queue.
